export const settingCompanySelector = (state) => state.settings.company;
export const isLoadingSelector = (state) => state.settings.loading;
export const isShowSnackbar = (state) => state.settings.snackbarShow;
export const snackbarType = (state) => state.settings.snackbarType;
export const snackbarText = (state) => state.settings.snackbarText;
export const settingWorkTime = (state) => state.settings.workTime;
export const securityCompanySelector = (state) => state.settings.security;
export const categoriesSkillsSelector = (state) => state.settings.skills;
export const placesSelector = (state) => state.settings.places;