
export const GET_SETTINGS_COMPANY = 'GET_SETTINGS_COMPANY';
export const GET_SETTINGS_COMPANY_SUCCESS = 'GET_SETTINGS_COMPANY_SUCCESS';
export const GET_SETTINGS_COMPANY_ERROR = 'GET_SETTINGS_COMPANY_ERROR';