
export const GET_SETTINGS_COMPANY = 'GET_SETTINGS_COMPANY';
export const GET_SETTINGS_COMPANY_SUCCESS = 'GET_SETTINGS_COMPANY_SUCCESS';
export const GET_SETTINGS_COMPANY_ERROR = 'GET_SETTINGS_COMPANY_ERROR';

export const PATCH_SETTINGS_COMPANY = 'PATCH_SETTINGS_COMPANY';
export const PATCH_SETTINGS_COMPANY_SUCCESS = 'PATCH_SETTINGS_COMPANY_SUCCESS';
export const PATCH_SETTINGS_COMPANY_ERROR = 'PATCH_SETTINGS_COMPANY_ERROR';

export const ADD_SETTING_SNACKBAR = 'ADD_SETTING_SNACKBAR';
export const DISMISS_SETTING_SNACKBAR = 'DISMISS_SETTING_SNACKBAR ';

export const GET_WORK_TIME = 'GET_WORK_TIME';
export const GET_WORK_TIME_SUCCESS = 'GET_WORK_TIME_SUCCESS';

export const PATCH_WORK_TIME = 'PATCH_WORK_TIME';
export const PATCH_WORK_TIME_SUCCESS = 'PATCH_WORK_TIME_SUCCESS';
export const PATCH_WORK_TIME_ERROR = 'PATCH_WORK_TIME_ERROR';

export const ADD_HOLIDAY = 'ADD_HOLIDAY';
export const ADD_HOLIDAY_SUCCESS = 'ADD_HOLIDAY_SUCCESS';
export const ADD_HOLIDAY_ERROR = 'ADD_HOLIDAY_ERROR';

export const DELETE_HOLIDAY = 'DELETE_HOLIDAY';
export const DELETE_HOLIDAY_SUCCESS = 'DELETE_HOLIDAY_SUCCESS';
export const DELETE_HOLIDAY_ERROR = 'DELETE_HOLIDAY_ERROR';

export const GET_SECURITY_COMPANY = 'GET_SECURITY_COMPANY';
export const GET_SECURITY_COMPANY_SUCCESS = 'GET_SECURITY_COMPANY_SUCCESS';
export const GET_SECURITY_COMPANY_ERROR = 'GET_SECURITY_COMPANY_ERROR';