export const GET_SCHEDULE = 'GET_SCHEDULE';
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS';
export const GET_SCHEDULE_ERROR = 'GET_SCHEDULE_ERROR';

export const POST_SHIFT = 'POST_SHIFT';
export const POST_SHIFT_SUCCESS = 'POST_SHIFT_SUCCESS';
export const POST_SHIFT_ERROR = 'POST_SHIFT_ERROR';

export const GET_SHIFT = 'GET_SHIFT';
export const GET_SHIFT_SUCCESS = 'GET_SHIFT_SUCCESS';
export const GET_SHIFT_ERROR = 'GET_SHIFT_ERROR';

export const PUT_SHIFT = 'PUT_SHIFT';
export const PUT_SHIFT_SUCCESS = 'PUT_SHIFT_SUCCESS';
export const PUT_SHIFT_ERROR = 'PUT_SHIFT_ERROR';

export const RESET_SHIFT = 'RESET_SHIFT';
