/* eslint-disable import/prefer-default-export */
export const GET_ORGANISATION_MODULES = 'GET_ORGANISATION_MODULES';
export const POST_SUPPORT_TICKET = 'POST_SUPPORT_TICKET';
export const POST_SUPPORT_TICKET_SUCCESS = 'POST_SUPPORT_TICKET_SUCCESS';
export const POST_SUPPORT_TICKET_ERROR = 'POST_SUPPORT_TICKET_ERROR';
export const DONE_SUPPORT_TICKET = 'DONE_SUPPORT_TICKET';
