export const EVENT_TYPE = {
  EARLY_CLOCK_IN: 1,
  LATE_CLOCK_IN: 2,
  MISSING_CLOCK_IN: 3,
  EARLY_CLOCK_OUT: 4,
  LATE_CLOCK_OUT: 5,
  MISSING_CLOCK_OUT: 6,
  DAILY_OVERTIME_START: 7,
  WEEKLY_OVERTIME_START: 8,
  REMINDER_TO_CLOCK_IN: 9,
  REMINDER_TO_CLOCK_OUT: 10,
};
