export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_ERROR = 'GET_COUNTRIES_ERROR';

export const POST_ORGANIZATION = 'POST_ORGANIZATION';
export const POST_ORGANIZATION_SUCCESS = 'POST_ORGANIZATION_SUCCESS';
export const POST_ORGANIZATION_ERROR = 'POST_ORGANIZATION_ERROR';

export const ADD_SNACKBAR = 'ADD_SNACKBAR';
export const DISMISS_SNACKBAR = 'DISMISS_SNACKBAR';

export const  GET_COMPANIES = 'GET_COMPANIES';
export const  GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';
export const  GET_COMPANIES_ERROR = 'GET_COMPANIES_ERROR';